name: Discord Notification

# Especifica os eventos que vão disparar a ação
on:
  push:
    branches:
      - main  # Monitora a branch 'main' para atualizações

jobs:
  notify-discord:
    runs-on: ubuntu-latest

    steps:
      # Ação que envia uma mensagem para o Discord quando um push ocorre
      - name: Send Discord Notification
        run: |
          curl -H "Content-Type: application/json" \
          -d "{\"content\": \"🚀 Novo push no repositório: ${{ github.repository }}.\\nÚltimo commit: ${{ github.event.head_commit.message }}.\\nData e hora do commit: ${{ github.event.head_commit.timestamp }}.\"}" \
          YOU_CANT_HAVE_MY_API
